// Design patterns GoF, présentés en fiches de référence. Modèle pur (aucun
// import Vue) : testable en Node. Tout le texte humain est bilingue {fr, en}.

export const FAMILIES = ['creational', 'structural', 'behavioral'];

export const PATTERNS = [
  {
    id: 'singleton',
    family: 'creational',
    name: { fr: 'Singleton', en: 'Singleton' },
    tagline: {
      fr: 'Garantir une seule instance et un point d\'accès global à celle-ci.',
      en: 'Ensure a class has one instance and a global access point to it.',
    },
    problem: {
      fr: 'Plusieurs parties du code créent chacune leur propre objet (connexion, config, cache) alors qu\'une seule instance partagée est voulue.',
      en: 'Several parts of the code each create their own object (connection, config, cache) when a single shared instance is intended.',
    },
    solution: {
      fr: 'Rendre le constructeur privé et exposer une méthode qui crée l\'instance au premier appel puis renvoie toujours la même.',
      en: 'Make the constructor private and expose a method that creates the instance on first call, then always returns the same one.',
    },
    when: {
      fr: 'Une ressource réellement unique (config appli, pool de connexions). À éviter comme variable globale déguisée : nuit aux tests.',
      en: 'A truly unique resource (app config, connection pool). Avoid it as a disguised global: it hurts testability.',
    },
    pitfalls: {
      fr: 'État global caché, couplage fort, problèmes de concurrence à l\'initialisation, tests difficiles à isoler.',
      en: 'Hidden global state, tight coupling, init-time concurrency issues, tests hard to isolate.',
    },
    pseudo: [
      'class Singleton',
      '    private static instance = null',
      '    private constructor() { }',
      '    static getInstance():',
      '        if instance is null:',
      '            instance = new Singleton()',
      '        return instance',
    ].join('\n'),
    code: {
      js: [
        'class Config {',
        '  static #instance;',
        '  static get() {',
        '    if (!Config.#instance) Config.#instance = new Config();',
        '    return Config.#instance;',
        '  }',
        '}',
        'Config.get() === Config.get(); // true',
      ].join('\n'),
      java: [
        'public final class Config {',
        '  private static Config instance;',
        '  private Config() {}',
        '  public static synchronized Config get() {',
        '    if (instance == null) instance = new Config();',
        '    return instance;',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'final class Config {',
        '  static let shared = Config()',
        '  private init() {}',
        '}',
        '// Config.shared est unique et thread-safe (let statique).',
      ].join('\n'),
      go: [
        'package config',
        'import "sync"',
        'var (instance *Config; once sync.Once)',
        'func Get() *Config {',
        '  once.Do(func() { instance = &Config{} })',
        '  return instance',
        '}',
      ].join('\n'),
      php: [
        'final class Config {',
        '  private static ?Config $instance = null;',
        '  private function __construct() {}',
        '  public static function get(): Config {',
        '    return self::$instance ??= new self();',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'require "singleton"',
        'class Config',
        '  include Singleton',
        'end',
        'Config.instance.equal?(Config.instance) # => true',
      ].join('\n'),
      csharp: [
        'public sealed class Config {',
        '  private static readonly Config _instance = new Config();',
        '  private Config() {}',
        '  public static Config Instance => _instance;',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'factory-method',
    family: 'creational',
    name: { fr: 'Factory Method', en: 'Factory Method' },
    tagline: {
      fr: 'Déléguer la création d\'objets à des sous-classes via une méthode dédiée.',
      en: 'Let subclasses decide which concrete object a creation method returns.',
    },
    problem: {
      fr: 'Du code fait `new Concret()` en dur un peu partout, ce qui rend impossible de faire varier le type produit sans modifier chaque appel.',
      en: 'Code does `new Concrete()` hardcoded everywhere, making it impossible to vary the produced type without touching every call site.',
    },
    solution: {
      fr: 'Une méthode `create()`, surchargée par chaque sous-classe, renvoie le bon produit derrière une interface commune.',
      en: 'A `create()` method, overridden by each subclass, returns the right product behind a common interface.',
    },
    when: {
      fr: 'Quand le type exact à instancier dépend du contexte ou de la sous-classe ; alternative propre aux gros `switch` de construction.',
      en: 'When the exact type to instantiate depends on context or subclass; a clean alternative to large construction `switch` statements.',
    },
    pitfalls: {
      fr: 'Prolifération de sous-classes pour de petites variations, hiérarchie de créateurs qui gonfle inutilement.',
      en: 'Subclass proliferation for small variations, creator hierarchy that grows needlessly.',
    },
    pseudo: [
      'abstract class Dialog',
      '    abstract createButton(): Button',
      '    render():',
      '        button = createButton()',
      '        button.draw()',
      '',
      'class WindowsDialog extends Dialog',
      '    createButton(): return new WinButton()',
    ].join('\n'),
    code: {
      js: [
        'class Dialog {',
        '  createButton() { throw new Error("override me"); }',
        '  render() { return this.createButton().draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  createButton() { return { draw: () => "web-button" }; }',
        '}',
        'new WebDialog().render(); // "web-button"',
      ].join('\n'),
      java: [
        'interface Button { String draw(); }',
        'abstract class Dialog {',
        '  abstract Button createButton();',
        '  String render() { return createButton().draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  Button createButton() { return () -> "web-button"; }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Button { func draw() -> String }',
        'class Dialog {',
        '  func createButton() -> Button { fatalError("override") }',
        '  func render() -> String { createButton().draw() }',
        '}',
        'class WebButton: Button { func draw() -> String { "web-button" } }',
        'class WebDialog: Dialog {',
        '  override func createButton() -> Button { WebButton() }',
        '}',
      ].join('\n'),
      go: [
        'type Button interface{ Draw() string }',
        'type Creator interface{ CreateButton() Button }',
        'type WebCreator struct{}',
        'func (WebCreator) CreateButton() Button { return webButton{} }',
        'type webButton struct{}',
        'func (webButton) Draw() string { return "web-button" }',
      ].join('\n'),
      php: [
        'interface Button { public function draw(): string; }',
        'abstract class Dialog {',
        '  abstract public function createButton(): Button;',
        '  public function render(): string { return $this->createButton()->draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  public function createButton(): Button { return new WebButton(); }',
        '}',
      ].join('\n'),
      ruby: [
        'class Dialog',
        '  def create_button = raise NotImplementedError',
        '  def render = create_button.draw',
        'end',
        '',
        'class WebDialog < Dialog',
        '  def create_button = WebButton.new',
        'end',
      ].join('\n'),
      csharp: [
        'interface IButton { string Draw(); }',
        'abstract class Dialog {',
        '  protected abstract IButton CreateButton();',
        '  public string Render() => CreateButton().Draw();',
        '}',
        'class WebDialog : Dialog {',
        '  protected override IButton CreateButton() => new WebButton();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'builder',
    family: 'creational',
    name: { fr: 'Builder', en: 'Builder' },
    tagline: {
      fr: 'Construire un objet complexe étape par étape via une API fluide.',
      en: 'Build a complex object step by step with a fluent API.',
    },
    problem: {
      fr: 'Un constructeur télescopique accumule dix paramètres, dont la plupart optionnels, devenant illisible et source d\'erreurs d\'ordre.',
      en: 'A telescoping constructor piles up ten parameters, most optional, becoming unreadable and error-prone regarding order.',
    },
    solution: {
      fr: 'Un builder expose des méthodes chaînées, une par champ optionnel, puis une méthode `build()` qui assemble l\'objet final.',
      en: 'A builder exposes chained methods, one per optional field, then a `build()` method that assembles the final object.',
    },
    when: {
      fr: 'Objets à nombreux champs optionnels ou immuables (requête HTTP, configuration, document composé).',
      en: 'Objects with many optional or immutable fields (HTTP request, configuration, composed document).',
    },
    pitfalls: {
      fr: 'Surcouche inutile pour des objets simples à peu de champs : le constructeur direct suffit alors.',
      en: 'Needless overhead for simple objects with few fields, where a plain constructor is already enough.',
    },
    pseudo: [
      'class BurgerBuilder',
      '    cheese(): this.hasCheese = true; return this',
      '    bacon(): this.hasBacon = true; return this',
      '    build(): return new Burger(this)',
      '',
      'burger = new BurgerBuilder().cheese().bacon().build()',
    ].join('\n'),
    code: {
      js: [
        'class BurgerBuilder {',
        '  #parts = [];',
        '  cheese() { this.#parts.push("cheese"); return this; }',
        '  bacon() { this.#parts.push("bacon"); return this; }',
        '  build() { return { parts: this.#parts }; }',
        '}',
        'new BurgerBuilder().cheese().bacon().build();',
      ].join('\n'),
      java: [
        'class Burger {',
        '  static class Builder {',
        '    private boolean cheese, bacon;',
        '    Builder cheese() { cheese = true; return this; }',
        '    Builder bacon() { bacon = true; return this; }',
        '    Burger build() { return new Burger(cheese, bacon); }',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'final class BurgerBuilder {',
        '  private var cheese = false, bacon = false',
        '  func withCheese() -> Self { cheese = true; return self }',
        '  func withBacon() -> Self { bacon = true; return self }',
        '  func build() -> Burger { Burger(cheese: cheese, bacon: bacon) }',
        '}',
      ].join('\n'),
      go: [
        'type BurgerBuilder struct{ cheese, bacon bool }',
        'func (b *BurgerBuilder) Cheese() *BurgerBuilder { b.cheese = true; return b }',
        'func (b *BurgerBuilder) Bacon() *BurgerBuilder { b.bacon = true; return b }',
        'func (b *BurgerBuilder) Build() Burger { return Burger{b.cheese, b.bacon} }',
      ].join('\n'),
      php: [
        'class BurgerBuilder {',
        '  private bool $cheese = false, $bacon = false;',
        '  public function cheese(): static { $this->cheese = true; return $this; }',
        '  public function bacon(): static { $this->bacon = true; return $this; }',
        '  public function build(): Burger { return new Burger($this->cheese, $this->bacon); }',
        '}',
      ].join('\n'),
      ruby: [
        'class BurgerBuilder',
        '  def cheese = (@cheese = true; self)',
        '  def bacon = (@bacon = true; self)',
        '  def build = Burger.new(cheese: @cheese, bacon: @bacon)',
        'end',
        '',
        'BurgerBuilder.new.cheese.bacon.build',
      ].join('\n'),
      csharp: [
        'class BurgerBuilder {',
        '  private bool _cheese, _bacon;',
        '  public BurgerBuilder Cheese() { _cheese = true; return this; }',
        '  public BurgerBuilder Bacon() { _bacon = true; return this; }',
        '  public Burger Build() => new Burger(_cheese, _bacon);',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'abstract-factory',
    family: 'creational',
    name: { fr: 'Abstract Factory', en: 'Abstract Factory' },
    tagline: {
      fr: 'Créer des familles d\'objets liés sans se coupler à leurs classes concrètes.',
      en: 'Create families of related objects without binding to their concrete classes.',
    },
    problem: {
      fr: 'Il faut produire des composants cohérents entre eux (bouton, case à cocher) pour un thème donné, sans mélanger les styles clair et sombre.',
      en: 'Components that must stay coherent with each other (button, checkbox) need to be produced for a given theme, without mixing light and dark styles.',
    },
    solution: {
      fr: 'Une interface de fabrique par famille (`UIFactory`) déclare `createButton()` et `createCheckbox()` ; chaque implémentation garantit un thème cohérent.',
      en: 'A factory interface per family (`UIFactory`) declares `createButton()` and `createCheckbox()`; each implementation guarantees a coherent theme.',
    },
    when: {
      fr: 'Plusieurs familles de produits interchangeables doivent coexister : thèmes UI, pilotes de systèmes de fichiers, drivers de base de données.',
      en: 'Several interchangeable product families must coexist: UI themes, filesystem drivers, database drivers.',
    },
    pitfalls: {
      fr: 'Ajouter un nouveau type de produit oblige à modifier l\'interface et toutes ses fabriques concrètes.',
      en: 'Adding a new product type forces changes to the interface and every one of its concrete factories.',
    },
    pseudo: [
      'interface UIFactory',
      '    createButton(): Button',
      '    createCheckbox(): Checkbox',
      '',
      'class DarkFactory implements UIFactory',
      '    createButton(): return new DarkButton()',
      '    createCheckbox(): return new DarkCheckbox()',
    ].join('\n'),
    code: {
      js: [
        'const LightFactory = {',
        '  createButton: () => ({ style: "light-button" }),',
        '  createCheckbox: () => ({ style: "light-checkbox" }),',
        '};',
        'const DarkFactory = {',
        '  createButton: () => ({ style: "dark-button" }),',
        '  createCheckbox: () => ({ style: "dark-checkbox" }),',
        '};',
      ].join('\n'),
      java: [
        'interface UIFactory {',
        '  Button createButton();',
        '  Checkbox createCheckbox();',
        '}',
        'class DarkFactory implements UIFactory {',
        '  public Button createButton() { return new DarkButton(); }',
        '  public Checkbox createCheckbox() { return new DarkCheckbox(); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol UIFactory {',
        '  func createButton() -> Button',
        '  func createCheckbox() -> Checkbox',
        '}',
        'struct DarkFactory: UIFactory {',
        '  func createButton() -> Button { DarkButton() }',
        '  func createCheckbox() -> Checkbox { DarkCheckbox() }',
        '}',
      ].join('\n'),
      go: [
        'type UIFactory interface {',
        '  CreateButton() Button',
        '  CreateCheckbox() Checkbox',
        '}',
        'type DarkFactory struct{}',
        'func (DarkFactory) CreateButton() Button { return DarkButton{} }',
        'func (DarkFactory) CreateCheckbox() Checkbox { return DarkCheckbox{} }',
      ].join('\n'),
      php: [
        'interface UIFactory {',
        '  public function createButton(): Button;',
        '  public function createCheckbox(): Checkbox;',
        '}',
        'class DarkFactory implements UIFactory {',
        '  public function createButton(): Button { return new DarkButton(); }',
        '  public function createCheckbox(): Checkbox { return new DarkCheckbox(); }',
        '}',
      ].join('\n'),
      ruby: [
        'module UIFactory',
        '  def create_button = raise NotImplementedError',
        '  def create_checkbox = raise NotImplementedError',
        'end',
        '',
        'class DarkFactory',
        '  include UIFactory',
        '  def create_button = DarkButton.new',
        '  def create_checkbox = DarkCheckbox.new',
        'end',
      ].join('\n'),
      csharp: [
        'interface IUIFactory {',
        '  IButton CreateButton();',
        '  ICheckbox CreateCheckbox();',
        '}',
        'class DarkFactory : IUIFactory {',
        '  public IButton CreateButton() => new DarkButton();',
        '  public ICheckbox CreateCheckbox() => new DarkCheckbox();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'adapter',
    family: 'structural',
    name: { fr: 'Adapter', en: 'Adapter' },
    tagline: {
      fr: 'Faire collaborer deux interfaces incompatibles via un adaptateur.',
      en: 'Make two incompatible interfaces work together via an adapter.',
    },
    problem: {
      fr: 'Une classe cliente attend une interface `ITarget`, mais le service disponible expose une API différente (legacy, tierce) qu\'on ne peut pas modifier.',
      en: 'A client class expects an `ITarget` interface, but the available service exposes a different API (legacy, third-party) that cannot be modified.',
    },
    solution: {
      fr: 'Un objet adaptateur implémente l\'interface attendue et traduit chaque appel vers la méthode correspondante du service enveloppé.',
      en: 'An adapter object implements the expected interface and translates each call into the corresponding method of the wrapped service.',
    },
    when: {
      fr: 'Intégrer une bibliothèque tierce ou un module legacy dont l\'API ne colle pas au contrat attendu par le reste du code.',
      en: 'Integrating a third-party library or a legacy module whose API does not match the contract expected by the rest of the code.',
    },
    pitfalls: {
      fr: 'Empiler les adaptateurs les uns sur les autres masque la dette technique au lieu de la résorber.',
      en: 'Stacking adapters on top of each other hides technical debt instead of resolving it.',
    },
    pseudo: [
      'interface ITarget',
      '    request(): string',
      '',
      'class SocketAdapter implements ITarget',
      '    constructor(legacy: OldSocket)',
      '    request(): return this.legacy.oldRequest()',
    ].join('\n'),
    code: {
      js: [
        'class OldSocket {',
        '  oldRequest() { return "legacy-data"; }',
        '}',
        'class SocketAdapter {',
        '  #legacy = new OldSocket();',
        '  request() { return this.#legacy.oldRequest(); }',
        '}',
        'new SocketAdapter().request(); // "legacy-data"',
      ].join('\n'),
      java: [
        'interface Target { String request(); }',
        'class OldSocket { String oldRequest() { return "legacy-data"; } }',
        'class SocketAdapter implements Target {',
        '  private final OldSocket legacy = new OldSocket();',
        '  public String request() { return legacy.oldRequest(); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Target { func request() -> String }',
        'final class OldSocket { func oldRequest() -> String { "legacy-data" } }',
        'final class SocketAdapter: Target {',
        '  private let legacy = OldSocket()',
        '  func request() -> String { legacy.oldRequest() }',
        '}',
      ].join('\n'),
      go: [
        'type Target interface{ Request() string }',
        'type OldSocket struct{}',
        'func (OldSocket) OldRequest() string { return "legacy-data" }',
        'type SocketAdapter struct{ legacy OldSocket }',
        'func (a SocketAdapter) Request() string { return a.legacy.OldRequest() }',
      ].join('\n'),
      php: [
        'interface Target { public function request(): string; }',
        'class OldSocket { public function oldRequest(): string { return "legacy-data"; } }',
        'class SocketAdapter implements Target {',
        '  public function __construct(private OldSocket $legacy) {}',
        '  public function request(): string { return $this->legacy->oldRequest(); }',
        '}',
      ].join('\n'),
      ruby: [
        'class OldSocket',
        '  def old_request = "legacy-data"',
        'end',
        '',
        'class SocketAdapter',
        '  def initialize(legacy = OldSocket.new) = @legacy = legacy',
        '  def request = @legacy.old_request',
        'end',
      ].join('\n'),
      csharp: [
        'interface ITarget { string Request(); }',
        'class OldSocket { public string OldRequest() => "legacy-data"; }',
        'class SocketAdapter : ITarget {',
        '  private readonly OldSocket _legacy = new OldSocket();',
        '  public string Request() => _legacy.OldRequest();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'decorator',
    family: 'structural',
    name: { fr: 'Decorator', en: 'Decorator' },
    tagline: {
      fr: 'Ajouter des comportements dynamiquement en emballant l\'objet.',
      en: 'Add behavior dynamically by wrapping the object.',
    },
    problem: {
      fr: 'Le nombre de sous-classes explose quand on veut combiner plusieurs options (café + lait + sucre, flux compressé et chiffré...).',
      en: 'The number of subclasses explodes when trying to combine several options (coffee + milk + sugar, compressed and encrypted stream...).',
    },
    solution: {
      fr: 'Des objets wrapper implémentent la même interface que l\'objet d\'origine, lui délèguent l\'appel puis ajoutent leur propre comportement.',
      en: 'Wrapper objects implement the same interface as the original object, delegate the call to it, then add their own behavior.',
    },
    when: {
      fr: 'Combiner librement des fonctionnalités indépendantes sans multiplier les sous-classes (flux compressé + chiffré, boissons personnalisables).',
      en: 'Freely combining independent features without multiplying subclasses (compressed + encrypted stream, customizable drinks).',
    },
    pitfalls: {
      fr: 'De longues chaînes de wrappers imbriqués deviennent difficiles à lire et à déboguer.',
      en: 'Long chains of nested wrappers become hard to read and debug.',
    },
    pseudo: [
      'interface Beverage',
      '    cost(): number',
      '',
      'class Milk implements Beverage',
      '    constructor(wrapped: Beverage)',
      '    cost(): return this.wrapped.cost() + 0.5',
      '',
      'total = new Milk(new Coffee()).cost()',
    ].join('\n'),
    code: {
      js: [
        'class Coffee {',
        '  cost() { return 2; }',
        '}',
        'class Milk {',
        '  #wrapped;',
        '  constructor(wrapped) { this.#wrapped = wrapped; }',
        '  cost() { return this.#wrapped.cost() + 0.5; }',
        '}',
        'new Milk(new Coffee()).cost(); // 2.5',
      ].join('\n'),
      java: [
        'interface Beverage { double cost(); }',
        'class Coffee implements Beverage { public double cost() { return 2; } }',
        'class Milk implements Beverage {',
        '  private final Beverage wrapped;',
        '  Milk(Beverage wrapped) { this.wrapped = wrapped; }',
        '  public double cost() { return wrapped.cost() + 0.5; }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Beverage { func cost() -> Double }',
        'struct Coffee: Beverage { func cost() -> Double { 2 } }',
        'struct Milk: Beverage {',
        '  let wrapped: Beverage',
        '  func cost() -> Double { wrapped.cost() + 0.5 }',
        '}',
        'Milk(wrapped: Coffee()).cost() // 2.5',
      ].join('\n'),
      go: [
        'type Beverage interface{ Cost() float64 }',
        'type Coffee struct{}',
        'func (Coffee) Cost() float64 { return 2 }',
        'type Milk struct{ Wrapped Beverage }',
        'func (m Milk) Cost() float64 { return m.Wrapped.Cost() + 0.5 }',
      ].join('\n'),
      php: [
        'interface Beverage { public function cost(): float; }',
        'class Coffee implements Beverage { public function cost(): float { return 2.0; } }',
        'class Milk implements Beverage {',
        '  public function __construct(private Beverage $wrapped) {}',
        '  public function cost(): float { return $this->wrapped->cost() + 0.5; }',
        '}',
      ].join('\n'),
      ruby: [
        'class Coffee',
        '  def cost = 2.0',
        'end',
        '',
        'class Milk',
        '  def initialize(wrapped) = @wrapped = wrapped',
        '  def cost = @wrapped.cost + 0.5',
        'end',
        '',
        'Milk.new(Coffee.new).cost # => 2.5',
      ].join('\n'),
      csharp: [
        'interface IBeverage { double Cost(); }',
        'class Coffee : IBeverage { public double Cost() => 2; }',
        'class Milk : IBeverage {',
        '  private readonly IBeverage _wrapped;',
        '  public Milk(IBeverage wrapped) { _wrapped = wrapped; }',
        '  public double Cost() => _wrapped.Cost() + 0.5;',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'facade',
    family: 'structural',
    name: { fr: 'Facade', en: 'Facade' },
    tagline: {
      fr: 'Offrir une interface simple par-dessus un sous-système complexe.',
      en: 'Provide a simple interface over a complex subsystem.',
    },
    problem: {
      fr: 'Pour effectuer une opération métier simple, le client doit orchestrer lui-même plusieurs classes bas niveau dans le bon ordre.',
      en: 'To perform a simple business operation, the client has to orchestrate several low-level classes itself, in the right order.',
    },
    solution: {
      fr: 'Une classe façade expose une méthode unique et lisible, qui appelle en interne les composants du sous-système à sa place.',
      en: 'A facade class exposes a single, readable method that internally calls the subsystem\'s components on the client\'s behalf.',
    },
    when: {
      fr: 'Simplifier l\'usage d\'une API compliquée ou d\'un ensemble de bibliothèques (lecture de fichier multimédia, appel à un framework verbeux).',
      en: 'Simplifying the use of a complicated API or a set of libraries (media file playback, calling a verbose framework).',
    },
    pitfalls: {
      fr: 'La façade grossit avec le temps et devient un objet-dieu qui connaît tout le sous-système.',
      en: 'The facade grows over time and becomes a god object that knows the entire subsystem.',
    },
    pseudo: [
      'class MediaFacade',
      '    play(file):',
      '        codec = CodecFactory.extract(file)',
      '        buffer = BufferReader.read(file)',
      '        AudioMixer.play(codec, buffer)',
      '',
      'new MediaFacade().play("song.mp3")',
    ].join('\n'),
    code: {
      js: [
        'class MediaFacade {',
        '  play(file) {',
        '    const codec = CodecFactory.extract(file);',
        '    const buffer = BufferReader.read(file);',
        '    return AudioMixer.play(codec, buffer);',
        '  }',
        '}',
        'new MediaFacade().play("song.mp3");',
      ].join('\n'),
      java: [
        'class MediaFacade {',
        '  void play(String file) {',
        '    String codec = CodecFactory.extract(file);',
        '    byte[] buffer = BufferReader.read(file);',
        '    AudioMixer.play(codec, buffer);',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'struct MediaFacade {',
        '  func play(_ file: String) {',
        '    let codec = CodecFactory.extract(file)',
        '    let buffer = BufferReader.read(file)',
        '    AudioMixer.play(codec, buffer)',
        '  }',
        '}',
      ].join('\n'),
      go: [
        'type MediaFacade struct{}',
        'func (MediaFacade) Play(file string) {',
        '  codec := CodecFactory{}.Extract(file)',
        '  buffer := BufferReader{}.Read(file)',
        '  AudioMixer{}.Play(codec, buffer)',
        '}',
      ].join('\n'),
      php: [
        'class MediaFacade {',
        '  public function play(string $file): void {',
        '    $codec = CodecFactory::extract($file);',
        '    $buffer = BufferReader::read($file);',
        '    AudioMixer::play($codec, $buffer);',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class MediaFacade',
        '  def play(file)',
        '    codec = CodecFactory.extract(file)',
        '    buffer = BufferReader.read(file)',
        '    AudioMixer.play(codec, buffer)',
        '  end',
        'end',
      ].join('\n'),
      csharp: [
        'class MediaFacade {',
        '  public void Play(string file) {',
        '    var codec = CodecFactory.Extract(file);',
        '    var buffer = BufferReader.Read(file);',
        '    AudioMixer.Play(codec, buffer);',
        '  }',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'proxy',
    family: 'structural',
    name: { fr: 'Proxy', en: 'Proxy' },
    tagline: {
      fr: 'Contrôler l\'accès à un objet (lazy, cache, sécurité).',
      en: 'Control access to an object (lazy loading, caching, protection).',
    },
    problem: {
      fr: 'L\'objet réel est coûteux à créer, distant, ou sensible, et on veut retarder ou surveiller son utilisation sans changer le code client.',
      en: 'The real object is expensive to create, remote, or sensitive, and its use needs delaying or monitoring without changing the client code.',
    },
    solution: {
      fr: 'Un proxy implémentant la même interface intercepte les appels et gère l\'accès (création différée, cache, vérification de droits) avant de déléguer.',
      en: 'A proxy implementing the same interface intercepts calls and manages access (deferred creation, caching, permission checks) before delegating.',
    },
    when: {
      fr: 'Chargement paresseux d\'une image lourde, cache de résultats coûteux, contrôle d\'accès à une ressource protégée.',
      en: 'Lazy loading of a heavy image, caching of expensive results, access control over a protected resource.',
    },
    pitfalls: {
      fr: 'Le proxy ajoute une couche d\'indirection et une latence cachée qui peuvent surprendre au débogage.',
      en: 'The proxy adds a layer of indirection and hidden latency that can be surprising when debugging.',
    },
    pseudo: [
      'interface Image',
      '    display()',
      '',
      'class ImageProxy implements Image',
      '    private real = null',
      '    display():',
      '        if real is null: real = new RealImage(this.file)',
      '        real.display()',
    ].join('\n'),
    code: {
      js: [
        'class RealImage {',
        '  constructor(file) { this.file = file; console.log("load", file); }',
        '  display() { return `showing ${this.file}`; }',
        '}',
        'class ImageProxy {',
        '  #real;',
        '  constructor(file) { this.file = file; }',
        '  display() { return (this.#real ??= new RealImage(this.file)).display(); }',
        '}',
      ].join('\n'),
      java: [
        'interface Image { String display(); }',
        'class RealImage implements Image {',
        '  RealImage(String file) { /* chargement coûteux */ }',
        '  public String display() { return "showing"; }',
        '}',
        'class ImageProxy implements Image {',
        '  private RealImage real;',
        '  private final String file;',
        '  ImageProxy(String file) { this.file = file; }',
        '  public String display() {',
        '    if (real == null) real = new RealImage(file);',
        '    return real.display();',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Image { func display() -> String }',
        'final class RealImage: Image {',
        '  init(_ file: String) { /* chargement coûteux */ }',
        '  func display() -> String { "showing" }',
        '}',
        'final class ImageProxy: Image {',
        '  private var real: RealImage?',
        '  private let file: String',
        '  init(_ file: String) { self.file = file }',
        '  func display() -> String {',
        '    if real == nil { real = RealImage(file) }',
        '    return real!.display()',
        '  }',
        '}',
      ].join('\n'),
      go: [
        'type Image interface{ Display() string }',
        'type RealImage struct{ File string }',
        'func (RealImage) Display() string { return "showing" }',
        'type ImageProxy struct {',
        '  File string',
        '  real *RealImage',
        '}',
        'func (p *ImageProxy) Display() string {',
        '  if p.real == nil { p.real = &RealImage{p.File} }',
        '  return p.real.Display()',
        '}',
      ].join('\n'),
      php: [
        'interface Image { public function display(): string; }',
        'class RealImage implements Image {',
        '  public function __construct(private string $file) {}',
        '  public function display(): string { return "showing {$this->file}"; }',
        '}',
        'class ImageProxy implements Image {',
        '  private ?RealImage $real = null;',
        '  public function __construct(private string $file) {}',
        '  public function display(): string {',
        '    return ($this->real ??= new RealImage($this->file))->display();',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class RealImage',
        '  def initialize(file) = @file = file',
        '  def display = "showing #{@file}"',
        'end',
        '',
        'class ImageProxy',
        '  def initialize(file) = @file = file',
        '  def display = (@real ||= RealImage.new(@file)).display',
        'end',
      ].join('\n'),
      csharp: [
        'interface IImage { string Display(); }',
        'class RealImage : IImage {',
        '  private readonly string _file;',
        '  public RealImage(string file) { _file = file; }',
        '  public string Display() => $"showing {_file}";',
        '}',
        'class ImageProxy : IImage {',
        '  private RealImage? _real;',
        '  private readonly string _file;',
        '  public ImageProxy(string file) { _file = file; }',
        '  public string Display() => (_real ??= new RealImage(_file)).Display();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'composite',
    family: 'structural',
    name: { fr: 'Composite', en: 'Composite' },
    tagline: {
      fr: 'Traiter uniformément objets simples et compositions en arbre.',
      en: 'Treat individual objects and compositions uniformly as a tree.',
    },
    problem: {
      fr: 'Le code doit distinguer partout une feuille (fichier) d\'une branche (dossier), avec des cas particuliers qui se répètent à chaque parcours.',
      en: 'The code has to distinguish a leaf (file) from a branch (folder) everywhere, with special cases repeated at every traversal.',
    },
    solution: {
      fr: 'Une interface commune `Component` déclare une opération (`size()`) implémentée aussi bien par les feuilles que par les branches, qui délèguent à leurs enfants.',
      en: 'A common `Component` interface declares an operation (`size()`) implemented both by leaves and by branches, which delegate to their children.',
    },
    when: {
      fr: 'Structures arborescentes récursives : fichiers/dossiers, arbre de composants d\'interface, menus imbriqués.',
      en: 'Recursive tree-like structures: files/folders, UI component trees, nested menus.',
    },
    pitfalls: {
      fr: 'Une interface trop générale force les feuilles à implémenter des méthodes comme `add()` qui n\'ont pas de sens pour elles.',
      en: 'An overly general interface forces leaves to implement methods like `add()` that make no sense for them.',
    },
    pseudo: [
      'interface Component',
      '    size(): number',
      '',
      'class File implements Component',
      '    size(): return this.bytes',
      '',
      'class Folder implements Component',
      '    children: Component[]',
      '    size(): return sum(c.size() for c in children)',
    ].join('\n'),
    code: {
      js: [
        'class File {',
        '  constructor(bytes) { this.bytes = bytes; }',
        '  size() { return this.bytes; }',
        '}',
        'class Folder {',
        '  #children = [];',
        '  add(child) { this.#children.push(child); return this; }',
        '  size() { return this.#children.reduce((s, c) => s + c.size(), 0); }',
        '}',
      ].join('\n'),
      java: [
        'interface Component { long size(); }',
        'class File implements Component {',
        '  private final long bytes;',
        '  File(long bytes) { this.bytes = bytes; }',
        '  public long size() { return bytes; }',
        '}',
        'class Folder implements Component {',
        '  private final List<Component> children = new ArrayList<>();',
        '  void add(Component c) { children.add(c); }',
        '  public long size() { return children.stream().mapToLong(Component::size).sum(); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Component { func size() -> Int }',
        'struct FileLeaf: Component {',
        '  let bytes: Int',
        '  func size() -> Int { bytes }',
        '}',
        'final class Folder: Component {',
        '  var children: [Component] = []',
        '  func size() -> Int { children.reduce(0) { $0 + $1.size() } }',
        '}',
      ].join('\n'),
      go: [
        'type Component interface{ Size() int }',
        'type File struct{ Bytes int }',
        'func (f File) Size() int { return f.Bytes }',
        'type Folder struct{ Children []Component }',
        'func (f Folder) Size() int {',
        '  total := 0',
        '  for _, c := range f.Children { total += c.Size() }',
        '  return total',
        '}',
      ].join('\n'),
      php: [
        'interface Component { public function size(): int; }',
        'class FileLeaf implements Component {',
        '  public function __construct(private int $bytes) {}',
        '  public function size(): int { return $this->bytes; }',
        '}',
        'class Folder implements Component {',
        '  private array $children = [];',
        '  public function add(Component $c): void { $this->children[] = $c; }',
        '  public function size(): int {',
        '    return array_sum(array_map(fn($c) => $c->size(), $this->children));',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class FileLeaf',
        '  def initialize(bytes) = @bytes = bytes',
        '  def size = @bytes',
        'end',
        '',
        'class Folder',
        '  def initialize = @children = []',
        '  def add(child) = @children << child',
        '  def size = @children.sum(&:size)',
        'end',
      ].join('\n'),
      csharp: [
        'interface IComponent { int Size(); }',
        'class FileLeaf : IComponent {',
        '  private readonly int _bytes;',
        '  public FileLeaf(int bytes) { _bytes = bytes; }',
        '  public int Size() => _bytes;',
        '}',
        'class Folder : IComponent {',
        '  private readonly List<IComponent> _children = new();',
        '  public void Add(IComponent c) => _children.Add(c);',
        '  public int Size() => _children.Sum(c => c.Size());',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'strategy',
    family: 'behavioral',
    name: { fr: 'Strategy', en: 'Strategy' },
    tagline: {
      fr: 'Interchanger des algorithmes derrière une interface commune.',
      en: 'Swap algorithms behind a common interface.',
    },
    problem: {
      fr: 'Une méthode contient un gros `if/switch` qui choisit l\'algorithme à appliquer (tri, calcul de prix, paiement), ce qui rend chaque ajout de variante plus risqué.',
      en: 'A method contains a large `if/switch` that picks which algorithm to apply (sorting, pricing, payment), making every new variant riskier to add.',
    },
    solution: {
      fr: 'Chaque algorithme devient une classe qui implémente une interface commune ; le contexte détient une référence vers la stratégie courante et lui délègue le travail.',
      en: 'Each algorithm becomes a class implementing a common interface; the context holds a reference to the current strategy and delegates the work to it.',
    },
    when: {
      fr: 'Plusieurs variantes d\'un même traitement doivent coexister et être choisies dynamiquement (tri, calcul de prix, moyen de paiement).',
      en: 'Several variants of the same operation must coexist and be selected dynamically (sorting, pricing, payment method).',
    },
    pitfalls: {
      fr: 'Multiplication de petites classes pour des variantes très simples, et le client doit connaître les stratégies disponibles pour choisir la bonne.',
      en: 'Proliferation of small classes for very simple variants, and the client must know the available strategies to pick the right one.',
    },
    pseudo: [
      'interface PaymentStrategy',
      '    pay(amount): void',
      '',
      'class Cart',
      '    constructor(strategy: PaymentStrategy)',
      '    checkout(amount): this.strategy.pay(amount)',
      '',
      'new Cart(new Paypal()).checkout(42)',
    ].join('\n'),
    code: {
      js: [
        'class Paypal {',
        '  pay(amount) { return `paypal:${amount}`; }',
        '}',
        'class Cart {',
        '  #strategy;',
        '  setStrategy(strategy) { this.#strategy = strategy; return this; }',
        '  pay(amount) { return this.#strategy.pay(amount); }',
        '}',
        'new Cart().setStrategy(new Paypal()).pay(42);',
      ].join('\n'),
      java: [
        'interface PaymentStrategy { String pay(int amount); }',
        'class Paypal implements PaymentStrategy {',
        '  public String pay(int amount) { return "paypal:" + amount; }',
        '}',
        'class Cart {',
        '  private PaymentStrategy strategy;',
        '  void setStrategy(PaymentStrategy s) { strategy = s; }',
        '  String pay(int amount) { return strategy.pay(amount); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol PaymentStrategy { func pay(_ amount: Int) -> String }',
        'struct Paypal: PaymentStrategy {',
        '  func pay(_ amount: Int) -> String { "paypal:\\(amount)" }',
        '}',
        'final class Cart {',
        '  private var strategy: PaymentStrategy?',
        '  func setStrategy(_ s: PaymentStrategy) -> Self { strategy = s; return self }',
        '  func pay(_ amount: Int) -> String? { strategy?.pay(amount) }',
        '}',
      ].join('\n'),
      go: [
        'package payment',
        'import "fmt"',
        'type PaymentStrategy interface{ Pay(amount int) string }',
        'type Paypal struct{}',
        'func (Paypal) Pay(amount int) string { return fmt.Sprintf("paypal:%d", amount) }',
        'type Cart struct{ strategy PaymentStrategy }',
        'func (c *Cart) SetStrategy(s PaymentStrategy) { c.strategy = s }',
        'func (c *Cart) Pay(amount int) string { return c.strategy.Pay(amount) }',
      ].join('\n'),
      php: [
        'interface PaymentStrategy { public function pay(int $amount): string; }',
        'class Paypal implements PaymentStrategy {',
        '  public function pay(int $amount): string { return "paypal:$amount"; }',
        '}',
        'class Cart {',
        '  private PaymentStrategy $strategy;',
        '  public function setStrategy(PaymentStrategy $s): static { $this->strategy = $s; return $this; }',
        '  public function pay(int $amount): string { return $this->strategy->pay($amount); }',
        '}',
      ].join('\n'),
      ruby: [
        'class Paypal',
        '  def pay(amount) = "paypal:#{amount}"',
        'end',
        '',
        'class Cart',
        '  def set_strategy(strategy) = (@strategy = strategy; self)',
        '  def pay(amount) = @strategy.pay(amount)',
        'end',
        '',
        'Cart.new.set_strategy(Paypal.new).pay(42)',
      ].join('\n'),
      csharp: [
        'interface IPaymentStrategy { string Pay(int amount); }',
        'class Paypal : IPaymentStrategy {',
        '  public string Pay(int amount) => $"paypal:{amount}";',
        '}',
        'class Cart {',
        '  private IPaymentStrategy _strategy;',
        '  public Cart SetStrategy(IPaymentStrategy s) { _strategy = s; return this; }',
        '  public string Pay(int amount) => _strategy.Pay(amount);',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'observer',
    family: 'behavioral',
    name: { fr: 'Observer', en: 'Observer' },
    tagline: {
      fr: 'Notifier automatiquement des abonnés lors d\'un changement.',
      en: 'Notify subscribers automatically when state changes.',
    },
    problem: {
      fr: 'L\'émetteur d\'un événement doit connaître et appeler directement chaque destinataire intéressé, ce qui le couple fortement à eux.',
      en: 'The event emitter has to know and directly call every interested receiver, tightly coupling it to each of them.',
    },
    solution: {
      fr: 'Le sujet maintient une liste d\'observateurs auxquels il s\'abonne dynamiquement, puis les notifie tous via une méthode `notify()` lors d\'un changement.',
      en: 'The subject maintains a list of observers that subscribe dynamically, then notifies all of them via a `notify()` method whenever something changes.',
    },
    when: {
      fr: 'Systèmes d\'événements, interfaces réactives, publication/abonnement entre modules découplés.',
      en: 'Event systems, reactive UIs, publish/subscribe between decoupled modules.',
    },
    pitfalls: {
      fr: 'Fuites mémoire si un observateur oublie de se désabonner, et ordre de notification parfois difficile à prévoir.',
      en: 'Memory leaks when an observer forgets to unsubscribe, and notification order that can be hard to predict.',
    },
    pseudo: [
      'class Subject',
      '    observers = []',
      '    subscribe(fn): this.observers.push(fn)',
      '    emit(data): for obs in observers: obs(data)',
      '',
      'subject.subscribe(fn)',
      'subject.emit(x)',
    ].join('\n'),
    code: {
      js: [
        'class Subject {',
        '  #observers = [];',
        '  subscribe(fn) { this.#observers.push(fn); return () => this.#observers = this.#observers.filter((o) => o !== fn); }',
        '  emit(data) { this.#observers.forEach((fn) => fn(data)); }',
        '}',
        'const subject = new Subject();',
        'subject.subscribe((x) => console.log(x));',
        'subject.emit("changed");',
      ].join('\n'),
      java: [
        'interface Observer { void update(String data); }',
        'class Subject {',
        '  private final List<Observer> observers = new ArrayList<>();',
        '  void subscribe(Observer o) { observers.add(o); }',
        '  void emit(String data) { observers.forEach((o) -> o.update(data)); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Observer { func update(_ data: String) }',
        'final class Subject {',
        '  private var observers: [Observer] = []',
        '  func subscribe(_ o: Observer) { observers.append(o) }',
        '  func emit(_ data: String) { observers.forEach { $0.update(data) } }',
        '}',
      ].join('\n'),
      go: [
        'type Observer func(data string)',
        'type Subject struct{ observers []Observer }',
        'func (s *Subject) Subscribe(o Observer) { s.observers = append(s.observers, o) }',
        'func (s *Subject) Emit(data string) {',
        '  for _, o := range s.observers { o(data) }',
        '}',
      ].join('\n'),
      php: [
        'class Subject {',
        '  private array $observers = [];',
        '  public function subscribe(callable $fn): void { $this->observers[] = $fn; }',
        '  public function emit(string $data): void {',
        '    foreach ($this->observers as $fn) { $fn($data); }',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class Subject',
        '  def initialize = @observers = []',
        '  def subscribe(&fn) = @observers << fn',
        '  def emit(data) = @observers.each { |fn| fn.call(data) }',
        'end',
        '',
        'subject = Subject.new',
        'subject.subscribe { |x| puts x }',
        'subject.emit("changed")',
      ].join('\n'),
      csharp: [
        'class Subject {',
        '  public event Action<string>? Changed;',
        '  public void Subscribe(Action<string> fn) => Changed += fn;',
        '  public void Emit(string data) => Changed?.Invoke(data);',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'command',
    family: 'behavioral',
    name: { fr: 'Command', en: 'Command' },
    tagline: {
      fr: 'Encapsuler une action en objet (annulable, mise en file).',
      en: 'Encapsulate an action as an object (undo, queue).',
    },
    problem: {
      fr: 'Le bouton d\'interface appelle directement la logique métier, ce qui empêche de mettre en file, journaliser ou annuler l\'action.',
      en: 'The UI button calls business logic directly, which prevents queuing, logging, or undoing the action.',
    },
    solution: {
      fr: 'Chaque action devient un objet commande avec une méthode `execute()` (et souvent `undo()`), stocké et rejoué par un invocateur.',
      en: 'Each action becomes a command object with an `execute()` method (and often `undo()`), stored and replayed by an invoker.',
    },
    when: {
      fr: 'Historique annulable (undo/redo), files de tâches différées, macros combinant plusieurs actions.',
      en: 'Undoable history (undo/redo), deferred task queues, macros combining several actions.',
    },
    pitfalls: {
      fr: 'Verbosité excessive pour des actions triviales qui ne nécessitent ni annulation ni mise en file.',
      en: 'Excessive verbosity for trivial actions that need neither undo nor queuing.',
    },
    pseudo: [
      'interface Command',
      '    execute(): void',
      '    undo(): void',
      '',
      'class History',
      '    run(cmd: Command): cmd.execute(); this.stack.push(cmd)',
      '',
      'history.run(new AddText("hi"))',
    ].join('\n'),
    code: {
      js: [
        'class AddText {',
        '  constructor(doc, text) { this.doc = doc; this.text = text; }',
        '  execute() { this.doc.content += this.text; }',
        '  undo() { this.doc.content = this.doc.content.slice(0, -this.text.length); }',
        '}',
        'class History {',
        '  #stack = [];',
        '  run(cmd) { cmd.execute(); this.#stack.push(cmd); }',
        '  undoLast() { this.#stack.pop()?.undo(); }',
        '}',
      ].join('\n'),
      java: [
        'interface Command { void execute(); void undo(); }',
        'class AddText implements Command {',
        '  private final Document doc; private final String text;',
        '  AddText(Document doc, String text) { this.doc = doc; this.text = text; }',
        '  public void execute() { doc.append(text); }',
        '  public void undo() { doc.removeLast(text.length()); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Command { func execute(); func undo() }',
        'final class AddText: Command {',
        '  let doc: Document; let text: String',
        '  init(_ doc: Document, _ text: String) { self.doc = doc; self.text = text }',
        '  func execute() { doc.append(text) }',
        '  func undo() { doc.removeLast(text.count) }',
        '}',
      ].join('\n'),
      go: [
        'type Command interface{ Execute(); Undo() }',
        'type AddText struct{ Doc *Document; Text string }',
        'func (c AddText) Execute() { c.Doc.Append(c.Text) }',
        'func (c AddText) Undo() { c.Doc.RemoveLast(len(c.Text)) }',
        'type History struct{ stack []Command }',
        'func (h *History) Run(c Command) { c.Execute(); h.stack = append(h.stack, c) }',
      ].join('\n'),
      php: [
        'interface Command { public function execute(): void; public function undo(): void; }',
        'class AddText implements Command {',
        '  public function __construct(private Document $doc, private string $text) {}',
        '  public function execute(): void { $this->doc->append($this->text); }',
        '  public function undo(): void { $this->doc->removeLast(strlen($this->text)); }',
        '}',
      ].join('\n'),
      ruby: [
        'class AddText',
        '  def initialize(doc, text) = (@doc, @text = doc, text)',
        '  def execute = @doc.append(@text)',
        '  def undo = @doc.remove_last(@text.length)',
        'end',
        '',
        'class History',
        '  def initialize = @stack = []',
        '  def run(cmd) = (cmd.execute; @stack << cmd)',
        'end',
      ].join('\n'),
      csharp: [
        'interface ICommand { void Execute(); void Undo(); }',
        'class AddText : ICommand {',
        '  private readonly Document _doc; private readonly string _text;',
        '  public AddText(Document doc, string text) { _doc = doc; _text = text; }',
        '  public void Execute() => _doc.Append(_text);',
        '  public void Undo() => _doc.RemoveLast(_text.Length);',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'state',
    family: 'behavioral',
    name: { fr: 'State', en: 'State' },
    tagline: {
      fr: 'Changer le comportement d\'un objet selon son état interne.',
      en: 'Change an object\'s behavior as its internal state changes.',
    },
    problem: {
      fr: 'Chaque méthode répète un `switch(state)` pour adapter son comportement, et ajouter un état oblige à modifier toutes ces méthodes.',
      en: 'Every method repeats a `switch(state)` to adapt its behavior, and adding a state forces changes across all of them.',
    },
    solution: {
      fr: 'Chaque état devient une classe qui implémente les transitions possibles ; l\'objet délègue son comportement à l\'état courant et peut en changer dynamiquement.',
      en: 'Each state becomes a class implementing the possible transitions; the object delegates its behavior to the current state and can swap it dynamically.',
    },
    when: {
      fr: 'Machines à états explicites : lecteur média (lecture/pause/arrêt), cycle de vie d\'une commande.',
      en: 'Explicit state machines: media player (playing/paused/stopped), order lifecycle.',
    },
    pitfalls: {
      fr: 'La logique se disperse entre de nombreuses petites classes d\'état, rendant le flux global moins lisible d\'un coup d\'œil.',
      en: 'Logic gets scattered across many small state classes, making the overall flow harder to see at a glance.',
    },
    pseudo: [
      'interface State',
      '    press(player): void',
      '',
      'class Playing implements State',
      '    press(player): player.state = new Paused()',
      '',
      'player.press() // délègue à player.state.press(player)',
    ].join('\n'),
    code: {
      js: [
        'class Playing {',
        '  press(player) { player.state = new Paused(); return "pause"; }',
        '}',
        'class Paused {',
        '  press(player) { player.state = new Playing(); return "play"; }',
        '}',
        'class Player {',
        '  state = new Paused();',
        '  press() { return this.state.press(this); }',
        '}',
      ].join('\n'),
      java: [
        'interface State { void press(Player player); }',
        'class Playing implements State {',
        '  public void press(Player player) { player.setState(new Paused()); }',
        '}',
        'class Paused implements State {',
        '  public void press(Player player) { player.setState(new Playing()); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol State { func press(_ player: Player) }',
        'final class Playing: State {',
        '  func press(_ player: Player) { player.state = Paused() }',
        '}',
        'final class Paused: State {',
        '  func press(_ player: Player) { player.state = Playing() }',
        '}',
      ].join('\n'),
      go: [
        'type State interface{ Press(p *Player) }',
        'type Playing struct{}',
        'func (Playing) Press(p *Player) { p.State = Paused{} }',
        'type Paused struct{}',
        'func (Paused) Press(p *Player) { p.State = Playing{} }',
        'type Player struct{ State State }',
        'func (p *Player) Press() { p.State.Press(p) }',
      ].join('\n'),
      php: [
        'interface State { public function press(Player $player): void; }',
        'class PlayingState implements State {',
        '  public function press(Player $player): void { $player->setState(new PausedState()); }',
        '}',
        'class PausedState implements State {',
        '  public function press(Player $player): void { $player->setState(new PlayingState()); }',
        '}',
      ].join('\n'),
      ruby: [
        'class Playing',
        '  def press(player) = player.state = Paused.new',
        'end',
        '',
        'class Paused',
        '  def press(player) = player.state = Playing.new',
        'end',
        '',
        'class Player',
        '  attr_accessor :state',
        '  def press = state.press(self)',
        'end',
      ].join('\n'),
      csharp: [
        'interface IState { void Press(Player player); }',
        'class Playing : IState {',
        '  public void Press(Player player) => player.State = new Paused();',
        '}',
        'class Paused : IState {',
        '  public void Press(Player player) => player.State = new Playing();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'iterator',
    family: 'behavioral',
    name: { fr: 'Iterator', en: 'Iterator' },
    tagline: {
      fr: 'Parcourir une collection sans exposer sa structure interne.',
      en: 'Traverse a collection without exposing its internals.',
    },
    problem: {
      fr: 'Le code client dépend directement de la représentation interne de la collection (tableau, arbre, liste chaînée) pour la parcourir.',
      en: 'Client code depends directly on the collection\'s internal representation (array, tree, linked list) in order to traverse it.',
    },
    solution: {
      fr: 'Un itérateur expose une interface stable `hasNext()`/`next()` qui encapsule la logique de parcours, quelle que soit la structure sous-jacente.',
      en: 'An iterator exposes a stable `hasNext()`/`next()` interface that encapsulates the traversal logic, whatever the underlying structure.',
    },
    when: {
      fr: 'Exposer un parcours uniforme sur une structure interne qui peut évoluer librement (liste chaînée, arbre, flux paginé).',
      en: 'Exposing a uniform traversal over an internal structure that can evolve freely (linked list, tree, paginated stream).',
    },
    pitfalls: {
      fr: 'Réimplémenter un itérateur maison alors que le langage fournit déjà un protocole d\'itération natif.',
      en: 'Reimplementing a homemade iterator when the language already provides a native iteration protocol.',
    },
    pseudo: [
      'interface Iterator',
      '    hasNext(): boolean',
      '    next(): any',
      '',
      'class LinkedListIterator implements Iterator',
      '    hasNext(): return this.current != null',
      '    next(): value = this.current.value; this.current = this.current.next; return value',
    ].join('\n'),
    code: {
      js: [
        'class LinkedListIterator {',
        '  #current;',
        '  constructor(head) { this.#current = head; }',
        '  hasNext() { return this.#current !== null; }',
        '  next() { const v = this.#current.value; this.#current = this.#current.next; return v; }',
        '}',
        'const it = new LinkedListIterator(head);',
        'while (it.hasNext()) console.log(it.next());',
      ].join('\n'),
      java: [
        'class LinkedListIterator {',
        '  private Node current;',
        '  LinkedListIterator(Node head) { current = head; }',
        '  boolean hasNext() { return current != null; }',
        '  int next() {',
        '    int v = current.value; current = current.next; return v;',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'final class LinkedListIterator {',
        '  private var current: Node?',
        '  init(_ head: Node?) { current = head }',
        '  func hasNext() -> Bool { current != nil }',
        '  func next() -> Int {',
        '    let v = current!.value',
        '    current = current!.next',
        '    return v',
        '  }',
        '}',
      ].join('\n'),
      go: [
        'type ListIterator struct{ current *Node }',
        'func (it *ListIterator) HasNext() bool { return it.current != nil }',
        'func (it *ListIterator) Next() int {',
        '  v := it.current.Value',
        '  it.current = it.current.Next',
        '  return v',
        '}',
      ].join('\n'),
      php: [
        'class LinkedListIterator {',
        '  public function __construct(private ?Node $current) {}',
        '  public function hasNext(): bool { return $this->current !== null; }',
        '  public function next(): mixed {',
        '    $v = $this->current->value;',
        '    $this->current = $this->current->next;',
        '    return $v;',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class LinkedListIterator',
        '  def initialize(head) = @current = head',
        '  def has_next? = !@current.nil?',
        '  def next',
        '    value = @current.value',
        '    @current = @current.next',
        '    value',
        '  end',
        'end',
      ].join('\n'),
      csharp: [
        'class LinkedListIterator {',
        '  private Node? _current;',
        '  public LinkedListIterator(Node head) { _current = head; }',
        '  public bool HasNext() => _current != null;',
        '  public int Next() {',
        '    int v = _current!.Value;',
        '    _current = _current.Next;',
        '    return v;',
        '  }',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'template-method',
    family: 'behavioral',
    name: { fr: 'Template Method', en: 'Template Method' },
    tagline: {
      fr: 'Fixer le squelette d\'un algorithme, laisser des étapes redéfinissables.',
      en: 'Define an algorithm skeleton, let subclasses fill steps.',
    },
    problem: {
      fr: 'Plusieurs classes dupliquent le même enchaînement d\'étapes (parser, valider, sauvegarder) en ne variant que quelques détails.',
      en: 'Several classes duplicate the same sequence of steps (parse, validate, save) while varying only a few details.',
    },
    solution: {
      fr: 'Une méthode finale `generate()` fixe l\'ordre des étapes et appelle des méthodes abstraites (hooks) que chaque sous-classe redéfinit.',
      en: 'A final `generate()` method fixes the step order and calls abstract methods (hooks) that each subclass overrides.',
    },
    when: {
      fr: 'Pipelines à structure fixe avec variations locales : générer un rapport, parser un fichier puis valider puis sauvegarder.',
      en: 'Fixed-structure pipelines with local variations: generate a report, parse a file then validate then save.',
    },
    pitfalls: {
      fr: 'L\'héritage imposé est rigide ; Strategy est souvent préférable si les étapes doivent être combinées à l\'exécution.',
      en: 'The imposed inheritance is rigid; Strategy is often preferable when steps must be combined at runtime.',
    },
    pseudo: [
      'abstract class Report',
      '    generate():',
      '        this.header()',
      '        this.body()',
      '        this.footer()',
      '    abstract body(): void',
      '',
      'class SalesReport extends Report',
      '    body(): print("ventes du mois")',
    ].join('\n'),
    code: {
      js: [
        'class Report {',
        '  generate() { return [this.header(), this.body(), this.footer()].join("\\n"); }',
        '  header() { return "=== Report ==="; }',
        '  footer() { return "=== End ==="; }',
        '  body() { throw new Error("override me"); }',
        '}',
        'class SalesReport extends Report {',
        '  body() { return "ventes du mois"; }',
        '}',
      ].join('\n'),
      java: [
        'abstract class Report {',
        '  final String generate() { return header() + body() + footer(); }',
        '  String header() { return "=== Report ===\\n"; }',
        '  String footer() { return "\\n=== End ==="; }',
        '  abstract String body();',
        '}',
        'class SalesReport extends Report {',
        '  String body() { return "ventes du mois"; }',
        '}',
      ].join('\n'),
      swift: [
        'class Report {',
        '  final func generate() -> String { header() + body() + footer() }',
        '  func header() -> String { "=== Report ===\\n" }',
        '  func footer() -> String { "\\n=== End ===" }',
        '  func body() -> String { fatalError("override me") }',
        '}',
        'final class SalesReport: Report {',
        '  override func body() -> String { "ventes du mois" }',
        '}',
      ].join('\n'),
      go: [
        '// Go : composition/injection de fonction plutôt qu\'héritage',
        'type Report struct{ Body func() string }',
        'func (r Report) Header() string { return "=== Report ===" }',
        'func (r Report) Footer() string { return "=== End ===" }',
        'func (r Report) Generate() string {',
        '  return r.Header() + r.Body() + r.Footer()',
        '}',
        'sales := Report{Body: func() string { return "ventes du mois" }}',
      ].join('\n'),
      php: [
        'abstract class Report {',
        '  final public function generate(): string { return $this->header() . $this->body() . $this->footer(); }',
        '  protected function header(): string { return "=== Report ===\\n"; }',
        '  protected function footer(): string { return "\\n=== End ==="; }',
        '  abstract protected function body(): string;',
        '}',
        'class SalesReport extends Report {',
        '  protected function body(): string { return "ventes du mois"; }',
        '}',
      ].join('\n'),
      ruby: [
        'class Report',
        '  def generate = header + body + footer',
        '  def header = "=== Report ===\\n"',
        '  def footer = "\\n=== End ==="',
        '  def body = raise NotImplementedError',
        'end',
        '',
        'class SalesReport < Report',
        '  def body = "ventes du mois"',
        'end',
      ].join('\n'),
      csharp: [
        'abstract class Report {',
        '  public string Generate() => Header() + Body() + Footer();',
        '  protected virtual string Header() => "=== Report ===\\n";',
        '  protected virtual string Footer() => "\\n=== End ===";',
        '  protected abstract string Body();',
        '}',
        'class SalesReport : Report {',
        '  protected override string Body() => "ventes du mois";',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'chain-of-responsibility',
    family: 'behavioral',
    name: { fr: 'Chain of Responsibility', en: 'Chain of Responsibility' },
    tagline: {
      fr: 'Passer une requête le long d\'une chaîne de handlers.',
      en: 'Pass a request along a chain of handlers.',
    },
    problem: {
      fr: 'Un seul objet centralise toutes les conditions pour décider qui doit traiter une requête (authentification, quota, validation), ce qui le fait grossir sans fin.',
      en: 'A single object centralizes every condition to decide who should handle a request (authentication, quota, validation), making it grow endlessly.',
    },
    solution: {
      fr: 'Chaque handler décide de traiter la requête ou de la déléguer au suivant de la chaîne via `setNext()`.',
      en: 'Each handler decides to handle the request or to delegate it to the next one in the chain via `setNext()`.',
    },
    when: {
      fr: 'Middlewares HTTP, chaînes de validation, escalade de tickets support par niveau.',
      en: 'HTTP middlewares, validation chains, support ticket escalation by level.',
    },
    pitfalls: {
      fr: 'Une requête peut arriver en bout de chaîne sans qu\'aucun handler ne l\'ait traitée, silencieusement.',
      en: 'A request can reach the end of the chain without any handler having processed it, silently.',
    },
    pseudo: [
      'abstract class Handler',
      '    next: Handler = null',
      '    setNext(h): this.next = h; return h',
      '    handle(req):',
      '        if this.next: return this.next.handle(req)',
      '',
      'auth.setNext(rateLimit).setNext(handler)',
    ].join('\n'),
    code: {
      js: [
        'class Handler {',
        '  #next;',
        '  setNext(handler) { this.#next = handler; return handler; }',
        '  handle(req) { return this.#next?.handle(req); }',
        '}',
        'class AuthHandler extends Handler {',
        '  handle(req) { return req.token ? super.handle(req) : "401"; }',
        '}',
        'auth.setNext(rateLimit).setNext(finalHandler);',
      ].join('\n'),
      java: [
        'abstract class Handler {',
        '  protected Handler next;',
        '  Handler setNext(Handler h) { next = h; return h; }',
        '  String handle(Request req) { return next != null ? next.handle(req) : null; }',
        '}',
        'class AuthHandler extends Handler {',
        '  String handle(Request req) { return req.hasToken() ? super.handle(req) : "401"; }',
        '}',
      ].join('\n'),
      swift: [
        'class Handler {',
        '  var next: Handler?',
        '  @discardableResult func setNext(_ h: Handler) -> Handler { next = h; return h }',
        '  func handle(_ req: Request) -> String? { next?.handle(req) }',
        '}',
        'final class AuthHandler: Handler {',
        '  override func handle(_ req: Request) -> String? {',
        '    req.token != nil ? super.handle(req) : "401"',
        '  }',
        '}',
      ].join('\n'),
      go: [
        'type Handler interface{ Handle(req Request) string; SetNext(h Handler) }',
        'type AuthHandler struct{ next Handler }',
        'func (h *AuthHandler) SetNext(next Handler) { h.next = next }',
        'func (h *AuthHandler) Handle(req Request) string {',
        '  if req.Token == "" { return "401" }',
        '  if h.next != nil { return h.next.Handle(req) }',
        '  return "ok"',
        '}',
      ].join('\n'),
      php: [
        'abstract class Handler {',
        '  protected ?Handler $next = null;',
        '  public function setNext(Handler $h): Handler { $this->next = $h; return $h; }',
        '  public function handle(array $req): ?string { return $this->next?->handle($req); }',
        '}',
        'class AuthHandler extends Handler {',
        '  public function handle(array $req): ?string {',
        '    return isset($req["token"]) ? parent::handle($req) : "401";',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'class Handler',
        '  attr_accessor :next_handler',
        '  def set_next(handler) = (@next_handler = handler)',
        '  def handle(req) = next_handler&.handle(req)',
        'end',
        '',
        'class AuthHandler < Handler',
        '  def handle(req) = req[:token] ? super : "401"',
        'end',
      ].join('\n'),
      csharp: [
        'abstract class Handler {',
        '  protected Handler? Next;',
        '  public Handler SetNext(Handler h) { Next = h; return h; }',
        '  public virtual string? Handle(Request req) => Next?.Handle(req);',
        '}',
        'class AuthHandler : Handler {',
        '  public override string? Handle(Request req) => req.Token != null ? base.Handle(req) : "401";',
        '}',
      ].join('\n'),
    },
  },
];

export function patternsByFamily(fam) {
  return PATTERNS.filter((p) => p.family === fam);
}
