// Design patterns GoF, présentés en fiches de référence. Modèle pur (aucun
// import Vue) : testable en Node. Tout le texte humain est bilingue {fr, en}.

export const FAMILIES = ['creational', 'structural', 'behavioral'];

export const PATTERNS = [
  {
    id: 'singleton',
    family: 'creational',
    name: { fr: 'Singleton', en: 'Singleton' },
    tagline: {
      fr: 'Garantir une seule instance et un point d\'accès global à celle-ci.',
      en: 'Ensure a class has one instance and a global access point to it.',
    },
    problem: {
      fr: 'Plusieurs parties du code créent chacune leur propre objet (connexion, config, cache) alors qu\'une seule instance partagée est voulue.',
      en: 'Several parts of the code each create their own object (connection, config, cache) when a single shared instance is intended.',
    },
    solution: {
      fr: 'Rendre le constructeur privé et exposer une méthode qui crée l\'instance au premier appel puis renvoie toujours la même.',
      en: 'Make the constructor private and expose a method that creates the instance on first call, then always returns the same one.',
    },
    when: {
      fr: 'Une ressource réellement unique (config appli, pool de connexions). À éviter comme variable globale déguisée : nuit aux tests.',
      en: 'A truly unique resource (app config, connection pool). Avoid it as a disguised global: it hurts testability.',
    },
    pitfalls: {
      fr: 'État global caché, couplage fort, problèmes de concurrence à l\'initialisation, tests difficiles à isoler.',
      en: 'Hidden global state, tight coupling, init-time concurrency issues, tests hard to isolate.',
    },
    pseudo: [
      'class Singleton',
      '    private static instance = null',
      '    private constructor() { }',
      '    static getInstance():',
      '        if instance is null:',
      '            instance = new Singleton()',
      '        return instance',
    ].join('\n'),
    code: {
      js: [
        'class Config {',
        '  static #instance;',
        '  static get() {',
        '    if (!Config.#instance) Config.#instance = new Config();',
        '    return Config.#instance;',
        '  }',
        '}',
        'Config.get() === Config.get(); // true',
      ].join('\n'),
      java: [
        'public final class Config {',
        '  private static Config instance;',
        '  private Config() {}',
        '  public static synchronized Config get() {',
        '    if (instance == null) instance = new Config();',
        '    return instance;',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'final class Config {',
        '  static let shared = Config()',
        '  private init() {}',
        '}',
        '// Config.shared est unique et thread-safe (let statique).',
      ].join('\n'),
      go: [
        'package config',
        'import "sync"',
        'var (instance *Config; once sync.Once)',
        'func Get() *Config {',
        '  once.Do(func() { instance = &Config{} })',
        '  return instance',
        '}',
      ].join('\n'),
      php: [
        'final class Config {',
        '  private static ?Config $instance = null;',
        '  private function __construct() {}',
        '  public static function get(): Config {',
        '    return self::$instance ??= new self();',
        '  }',
        '}',
      ].join('\n'),
      ruby: [
        'require "singleton"',
        'class Config',
        '  include Singleton',
        'end',
        'Config.instance.equal?(Config.instance) # => true',
      ].join('\n'),
      csharp: [
        'public sealed class Config {',
        '  private static readonly Config _instance = new Config();',
        '  private Config() {}',
        '  public static Config Instance => _instance;',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'factory-method',
    family: 'creational',
    name: { fr: 'Factory Method', en: 'Factory Method' },
    tagline: {
      fr: 'Déléguer la création d\'objets à des sous-classes via une méthode dédiée.',
      en: 'Let subclasses decide which concrete object a creation method returns.',
    },
    problem: {
      fr: 'Du code fait `new Concret()` en dur un peu partout, ce qui rend impossible de faire varier le type produit sans modifier chaque appel.',
      en: 'Code does `new Concrete()` hardcoded everywhere, making it impossible to vary the produced type without touching every call site.',
    },
    solution: {
      fr: 'Une méthode `create()`, surchargée par chaque sous-classe, renvoie le bon produit derrière une interface commune.',
      en: 'A `create()` method, overridden by each subclass, returns the right product behind a common interface.',
    },
    when: {
      fr: 'Quand le type exact à instancier dépend du contexte ou de la sous-classe ; alternative propre aux gros `switch` de construction.',
      en: 'When the exact type to instantiate depends on context or subclass; a clean alternative to large construction `switch` statements.',
    },
    pitfalls: {
      fr: 'Prolifération de sous-classes pour de petites variations, hiérarchie de créateurs qui gonfle inutilement.',
      en: 'Subclass proliferation for small variations, creator hierarchy that grows needlessly.',
    },
    pseudo: [
      'abstract class Dialog',
      '    abstract createButton(): Button',
      '    render():',
      '        button = createButton()',
      '        button.draw()',
      '',
      'class WindowsDialog extends Dialog',
      '    createButton(): return new WinButton()',
    ].join('\n'),
    code: {
      js: [
        'class Dialog {',
        '  createButton() { throw new Error("override me"); }',
        '  render() { return this.createButton().draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  createButton() { return { draw: () => "web-button" }; }',
        '}',
        'new WebDialog().render(); // "web-button"',
      ].join('\n'),
      java: [
        'interface Button { String draw(); }',
        'abstract class Dialog {',
        '  abstract Button createButton();',
        '  String render() { return createButton().draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  Button createButton() { return () -> "web-button"; }',
        '}',
      ].join('\n'),
      swift: [
        'protocol Button { func draw() -> String }',
        'class Dialog {',
        '  func createButton() -> Button { fatalError("override") }',
        '  func render() -> String { createButton().draw() }',
        '}',
        'class WebButton: Button { func draw() -> String { "web-button" } }',
        'class WebDialog: Dialog {',
        '  override func createButton() -> Button { WebButton() }',
        '}',
      ].join('\n'),
      go: [
        'type Button interface{ Draw() string }',
        'type Creator interface{ CreateButton() Button }',
        'type WebCreator struct{}',
        'func (WebCreator) CreateButton() Button { return webButton{} }',
        'type webButton struct{}',
        'func (webButton) Draw() string { return "web-button" }',
      ].join('\n'),
      php: [
        'interface Button { public function draw(): string; }',
        'abstract class Dialog {',
        '  abstract public function createButton(): Button;',
        '  public function render(): string { return $this->createButton()->draw(); }',
        '}',
        'class WebDialog extends Dialog {',
        '  public function createButton(): Button { return new WebButton(); }',
        '}',
      ].join('\n'),
      ruby: [
        'class Dialog',
        '  def create_button = raise NotImplementedError',
        '  def render = create_button.draw',
        'end',
        '',
        'class WebDialog < Dialog',
        '  def create_button = WebButton.new',
        'end',
      ].join('\n'),
      csharp: [
        'interface IButton { string Draw(); }',
        'abstract class Dialog {',
        '  protected abstract IButton CreateButton();',
        '  public string Render() => CreateButton().Draw();',
        '}',
        'class WebDialog : Dialog {',
        '  protected override IButton CreateButton() => new WebButton();',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'builder',
    family: 'creational',
    name: { fr: 'Builder', en: 'Builder' },
    tagline: {
      fr: 'Construire un objet complexe étape par étape via une API fluide.',
      en: 'Build a complex object step by step with a fluent API.',
    },
    problem: {
      fr: 'Un constructeur télescopique accumule dix paramètres, dont la plupart optionnels, devenant illisible et source d\'erreurs d\'ordre.',
      en: 'A telescoping constructor piles up ten parameters, most optional, becoming unreadable and error-prone regarding order.',
    },
    solution: {
      fr: 'Un builder expose des méthodes chaînées, une par champ optionnel, puis une méthode `build()` qui assemble l\'objet final.',
      en: 'A builder exposes chained methods, one per optional field, then a `build()` method that assembles the final object.',
    },
    when: {
      fr: 'Objets à nombreux champs optionnels ou immuables (requête HTTP, configuration, document composé).',
      en: 'Objects with many optional or immutable fields (HTTP request, configuration, composed document).',
    },
    pitfalls: {
      fr: 'Surcouche inutile pour des objets simples à peu de champs : le constructeur direct suffit alors.',
      en: 'Needless overhead for simple objects with few fields, where a plain constructor is already enough.',
    },
    pseudo: [
      'class BurgerBuilder',
      '    cheese(): this.hasCheese = true; return this',
      '    bacon(): this.hasBacon = true; return this',
      '    build(): return new Burger(this)',
      '',
      'burger = new BurgerBuilder().cheese().bacon().build()',
    ].join('\n'),
    code: {
      js: [
        'class BurgerBuilder {',
        '  #parts = [];',
        '  cheese() { this.#parts.push("cheese"); return this; }',
        '  bacon() { this.#parts.push("bacon"); return this; }',
        '  build() { return { parts: this.#parts }; }',
        '}',
        'new BurgerBuilder().cheese().bacon().build();',
      ].join('\n'),
      java: [
        'class Burger {',
        '  static class Builder {',
        '    private boolean cheese, bacon;',
        '    Builder cheese() { cheese = true; return this; }',
        '    Builder bacon() { bacon = true; return this; }',
        '    Burger build() { return new Burger(cheese, bacon); }',
        '  }',
        '}',
      ].join('\n'),
      swift: [
        'final class BurgerBuilder {',
        '  private var cheese = false, bacon = false',
        '  func withCheese() -> Self { cheese = true; return self }',
        '  func withBacon() -> Self { bacon = true; return self }',
        '  func build() -> Burger { Burger(cheese: cheese, bacon: bacon) }',
        '}',
      ].join('\n'),
      go: [
        'type BurgerBuilder struct{ cheese, bacon bool }',
        'func (b *BurgerBuilder) Cheese() *BurgerBuilder { b.cheese = true; return b }',
        'func (b *BurgerBuilder) Bacon() *BurgerBuilder { b.bacon = true; return b }',
        'func (b *BurgerBuilder) Build() Burger { return Burger{b.cheese, b.bacon} }',
      ].join('\n'),
      php: [
        'class BurgerBuilder {',
        '  private bool $cheese = false, $bacon = false;',
        '  public function cheese(): static { $this->cheese = true; return $this; }',
        '  public function bacon(): static { $this->bacon = true; return $this; }',
        '  public function build(): Burger { return new Burger($this->cheese, $this->bacon); }',
        '}',
      ].join('\n'),
      ruby: [
        'class BurgerBuilder',
        '  def cheese = (@cheese = true; self)',
        '  def bacon = (@bacon = true; self)',
        '  def build = Burger.new(cheese: @cheese, bacon: @bacon)',
        'end',
        '',
        'BurgerBuilder.new.cheese.bacon.build',
      ].join('\n'),
      csharp: [
        'class BurgerBuilder {',
        '  private bool _cheese, _bacon;',
        '  public BurgerBuilder Cheese() { _cheese = true; return this; }',
        '  public BurgerBuilder Bacon() { _bacon = true; return this; }',
        '  public Burger Build() => new Burger(_cheese, _bacon);',
        '}',
      ].join('\n'),
    },
  },

  {
    id: 'abstract-factory',
    family: 'creational',
    name: { fr: 'Abstract Factory', en: 'Abstract Factory' },
    tagline: {
      fr: 'Créer des familles d\'objets liés sans se coupler à leurs classes concrètes.',
      en: 'Create families of related objects without binding to their concrete classes.',
    },
    problem: {
      fr: 'Il faut produire des composants cohérents entre eux (bouton, case à cocher) pour un thème donné, sans mélanger les styles clair et sombre.',
      en: 'Components that must stay coherent with each other (button, checkbox) need to be produced for a given theme, without mixing light and dark styles.',
    },
    solution: {
      fr: 'Une interface de fabrique par famille (`UIFactory`) déclare `createButton()` et `createCheckbox()` ; chaque implémentation garantit un thème cohérent.',
      en: 'A factory interface per family (`UIFactory`) declares `createButton()` and `createCheckbox()`; each implementation guarantees a coherent theme.',
    },
    when: {
      fr: 'Plusieurs familles de produits interchangeables doivent coexister : thèmes UI, pilotes de systèmes de fichiers, drivers de base de données.',
      en: 'Several interchangeable product families must coexist: UI themes, filesystem drivers, database drivers.',
    },
    pitfalls: {
      fr: 'Ajouter un nouveau type de produit oblige à modifier l\'interface et toutes ses fabriques concrètes.',
      en: 'Adding a new product type forces changes to the interface and every one of its concrete factories.',
    },
    pseudo: [
      'interface UIFactory',
      '    createButton(): Button',
      '    createCheckbox(): Checkbox',
      '',
      'class DarkFactory implements UIFactory',
      '    createButton(): return new DarkButton()',
      '    createCheckbox(): return new DarkCheckbox()',
    ].join('\n'),
    code: {
      js: [
        'const LightFactory = {',
        '  createButton: () => ({ style: "light-button" }),',
        '  createCheckbox: () => ({ style: "light-checkbox" }),',
        '};',
        'const DarkFactory = {',
        '  createButton: () => ({ style: "dark-button" }),',
        '  createCheckbox: () => ({ style: "dark-checkbox" }),',
        '};',
      ].join('\n'),
      java: [
        'interface UIFactory {',
        '  Button createButton();',
        '  Checkbox createCheckbox();',
        '}',
        'class DarkFactory implements UIFactory {',
        '  public Button createButton() { return new DarkButton(); }',
        '  public Checkbox createCheckbox() { return new DarkCheckbox(); }',
        '}',
      ].join('\n'),
      swift: [
        'protocol UIFactory {',
        '  func createButton() -> Button',
        '  func createCheckbox() -> Checkbox',
        '}',
        'struct DarkFactory: UIFactory {',
        '  func createButton() -> Button { DarkButton() }',
        '  func createCheckbox() -> Checkbox { DarkCheckbox() }',
        '}',
      ].join('\n'),
      go: [
        'type UIFactory interface {',
        '  CreateButton() Button',
        '  CreateCheckbox() Checkbox',
        '}',
        'type DarkFactory struct{}',
        'func (DarkFactory) CreateButton() Button { return DarkButton{} }',
        'func (DarkFactory) CreateCheckbox() Checkbox { return DarkCheckbox{} }',
      ].join('\n'),
      php: [
        'interface UIFactory {',
        '  public function createButton(): Button;',
        '  public function createCheckbox(): Checkbox;',
        '}',
        'class DarkFactory implements UIFactory {',
        '  public function createButton(): Button { return new DarkButton(); }',
        '  public function createCheckbox(): Checkbox { return new DarkCheckbox(); }',
        '}',
      ].join('\n'),
      ruby: [
        'module UIFactory',
        '  def create_button = raise NotImplementedError',
        '  def create_checkbox = raise NotImplementedError',
        'end',
        '',
        'class DarkFactory',
        '  include UIFactory',
        '  def create_button = DarkButton.new',
        '  def create_checkbox = DarkCheckbox.new',
        'end',
      ].join('\n'),
      csharp: [
        'interface IUIFactory {',
        '  IButton CreateButton();',
        '  ICheckbox CreateCheckbox();',
        '}',
        'class DarkFactory : IUIFactory {',
        '  public IButton CreateButton() => new DarkButton();',
        '  public ICheckbox CreateCheckbox() => new DarkCheckbox();',
        '}',
      ].join('\n'),
    },
  },
];

export function patternsByFamily(fam) {
  return PATTERNS.filter((p) => p.family === fam);
}
